@host = https://localhost:7210
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMTY0ZTE2NC1iM2YyLTQ2YmMtODhiMS0zNDg1ZWNmMDhhZjQiLCJqdGkiOiI0NTM2OGVhYWQ5ZDM0OGYxOWY0ZjFiMGI1NjFlOTg2ZCIsImlhdCI6MTc3NDI2NzM3NywibmFtZSI6IkphY2sgYkxVRSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6InN0dWRlbnQiLCJyb2xlIjoic3R1ZGVudCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMzE2NGUxNjQtYjNmMi00NmJjLTg4YjEtMzQ4NWVjZjA4YWY0IiwibmJmIjoxNzc0MjY3Mzc3LCJleHAiOjE3NzQ4NzIxNzcsImlzcyI6ImZwdHUtdG1vai1hcGkiLCJhdWQiOiJ0bW9qLXVzZXJzIn0.jgaUOa5Ssig1SoTP7pBOFoZHYjWKJFo-1hs_ds0FtiA
# @problemId = 8c54a739-8a7f-4bad-9da3-112df4b607b8
@problemId = 72b6514a-27c0-47b0-bb78-875967bf7fe0
@tagId1 = ddb3eac4-62d2-40af-98af-50c245887e54
@tagId2 = ddb3eac4-62d2-40af-98af-50c245887e54

### Create problem draft
POST {{host}}/api/v2/problems/drafts
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Two Sum Basic",
  "slug": "two-sum-basic-v2",
  "timeLimitMs": 1000,
  "memoryLimitKb": 262144,
  "typeCode": "algorithm",
  "scoringCode": "icpc",
  "visibilityCode": "private",
  "descriptionMd": "# Two Sum\n\nGiven an array of integers..."
}

### Get problem detail
GET {{host}}/api/v2/problems/{{problemId}}
Authorization: Bearer {{token}}

### Update content
PUT {{host}}/api/v2/problems/{{problemId}}/content
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Two Sum Basic Updated",
  "slug": "two-sum-basic-v2",
  "timeLimitMs": 1500,
  "memoryLimitKb": 262144,
  "typeCode": "algorithm",
  "scoringCode": "icpc",
  "visibilityCode": "private",
  "descriptionMd": "# Two Sum\n\n## Statement\nFind two numbers..."
}

### Create tag 1
POST {{host}}/api/v2/problems/tags
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Dynamic Programming v2",
  "slug": "dynamic-programming-v2"
}

### Create tag 2
POST {{host}}/api/v2/problems/tags
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Two Pointers v2",
  "slug": "two-pointers-v2"
}


### Set difficulty
PUT {{host}}/api/v2/problems/{{problemId}}/difficulty
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "difficulty": "easy"
}

### Attach tags
POST {{host}}/api/v2/problems/{{problemId}}/tags/attach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "tagIds": [
    "{{tagId1}}",
    "{{tagId2}}"
  ]
}

### Replace tags
PUT {{host}}/api/v2/problems/{{problemId}}/tags
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "tagIds": [
    "{{tagId1}}"
  ]
}